<?php

namespace ContainerYxEZofQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipeControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KmfN8.V.App\Controller\Admin\RecipeController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.KmfN8.V'] ?? $container->load('get_ServiceLocator_KmfN8_VService'));

        if (isset($container->privates['.service_locator.KmfN8.V.App\\Controller\\Admin\\RecipeController::edit()'])) {
            return $container->privates['.service_locator.KmfN8.V.App\\Controller\\Admin\\RecipeController::edit()'];
        }

        return $container->privates['.service_locator.KmfN8.V.App\\Controller\\Admin\\RecipeController::edit()'] = $a->withContext('App\\Controller\\Admin\\RecipeController::edit()', $container);
    }
}
