<?php

namespace ContainerYxEZofQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipesApiControllergetRecipeByIdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Tye6hqX.App\Controller\API\RecipesApiController::getRecipeById()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Tye6hqX.App\\Controller\\API\\RecipesApiController::getRecipeById()'] = ($container->privates['.service_locator.Tye6hqX'] ?? $container->load('get_ServiceLocator_Tye6hqXService'))->withContext('App\\Controller\\API\\RecipesApiController::getRecipeById()', $container);
    }
}
