<?php

namespace ContainerBD2IGAN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepartmentControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OPcyuNm.App\Controller\DepartmentController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OPcyuNm.App\\Controller\\DepartmentController::delete()'] = ($container->privates['.service_locator.OPcyuNm'] ?? $container->load('get_ServiceLocator_OPcyuNmService'))->withContext('App\\Controller\\DepartmentController::delete()', $container);
    }
}
