<?php

namespace ContainerBD2IGAN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerverifyUserEmailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fdTWzgN.App\Controller\RegistrationController::verifyUserEmail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fdTWzgN.App\\Controller\\RegistrationController::verifyUserEmail()'] = ($container->privates['.service_locator.fdTWzgN'] ?? $container->load('get_ServiceLocator_FdTWzgNService'))->withContext('App\\Controller\\RegistrationController::verifyUserEmail()', $container);
    }
}
