<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ4ku3kp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ4ku3kp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ4ku3kp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ4ku3kp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ4ku3kp\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z4ku3kp',
    'container.build_id' => 'f1325570',
    'container.build_time' => 1729684060,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ4ku3kp');
