<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAl3AlNB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAl3AlNB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAl3AlNB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAl3AlNB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAl3AlNB\App_KernelDevDebugContainer([
    'container.build_hash' => 'Al3AlNB',
    'container.build_id' => 'b3b661e7',
    'container.build_time' => 1732104438,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAl3AlNB');
