<?php

namespace ContainerOnkac38;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OPcyuNmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OPcyuNm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OPcyuNm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'department' => ['privates', '.errored..service_locator.OPcyuNm.App\\Entity\\Department', NULL, 'Cannot autowire service ".service_locator.OPcyuNm": it needs an instance of "App\\Entity\\Department" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'department' => 'App\\Entity\\Department',
            'entityManager' => '?',
        ]);
    }
}
