<?php

namespace ContainerOnkac38;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategory2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dsbOFwy.App\Entity\Category' shared service.
     *
     * @return \App\Entity\Category
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dsbOFwy": it needs an instance of "App\\Entity\\Category" but this type has been excluded in "config/services.yaml".');
    }
}
