<?php

namespace ContainerVGIZR2W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepartmentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9nJkjCo.App\Entity\Department' shared service.
     *
     * @return \App\Entity\Department
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9nJkjCo": it needs an instance of "App\\Entity\\Department" but this type has been excluded in "config/services.yaml".');
    }
}
