<?php

namespace ContainerAl3AlNB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUserControllercreateUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OxGaOcy.App\Controller\API\adminApi\ApiUserController::createUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OxGaOcy.App\\Controller\\API\\adminApi\\ApiUserController::createUser()'] = ($container->privates['.service_locator.OxGaOcy'] ?? $container->load('get_ServiceLocator_OxGaOcyService'))->withContext('App\\Controller\\API\\adminApi\\ApiUserController::createUser()', $container);
    }
}
