<?php

namespace ContainerAl3AlNB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipeControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KmfN8.V.App\Controller\Admin\RecipeController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KmfN8.V.App\\Controller\\Admin\\RecipeController::delete()'] = ($container->privates['.service_locator.KmfN8.V'] ?? $container->load('get_ServiceLocator_KmfN8_VService'))->withContext('App\\Controller\\Admin\\RecipeController::delete()', $container);
    }
}
