<?php

namespace ContainerAl3AlNB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipesApiControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yxa1ZOH.App\Controller\API\RecipesApiController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.yxa1ZOH'] ?? $container->load('get_ServiceLocator_Yxa1ZOHService'));

        if (isset($container->privates['.service_locator.yxa1ZOH.App\\Controller\\API\\RecipesApiController::create()'])) {
            return $container->privates['.service_locator.yxa1ZOH.App\\Controller\\API\\RecipesApiController::create()'];
        }

        return $container->privates['.service_locator.yxa1ZOH.App\\Controller\\API\\RecipesApiController::create()'] = $a->withContext('App\\Controller\\API\\RecipesApiController::create()', $container);
    }
}
